# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Metadata-DB-Search
version:      1.02
version_from: lib/Metadata/DB/Search.pm
installdirs:  site
requires:
    Cwd:                           3
    DBI:                           1
    LEOCHARRE::Class:              0
    LEOCHARRE::DEBUG:              1.11
    Metadata::DB:                  1.10
    Smart::Comments:               1
    Test::Simple:                  0.7

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
